config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :users do
    post 'add_tasks', on: :member
  end

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'how_it_works', to: 'pages#how_it_works'
  get '/dashboard', to: 'dashboard#index'

  get '/causes/:id/choose_cause', to: 'causes#choose_cause', as: 'choose_cause'
  # get '/causes/:id/choose_time', to: 'causes#choose_time',as: 'choose_time'

  resources :causes, only: %i[index show] do
    resources :tasks, only: %i[index create] do
    end
  end
end

app/models/action.rb
# frozen_string_literal: true

class Action < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cause.rb
# frozen_string_literal: true

class Cause < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_one_attached :photo
  # has_many :organisations
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :cause
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :cause
  has_many :actions
  has_many :users, through: :actions
  # has_one_attached :photo
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :actions
  has_many :tasks, through: :actions
  has_many :causes, through: :tasks
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :set_user, only: %i[index new create]
  # before_action :set_task, only: %i[index new create]

  def index
    @action = Action.all
  end

  def new
    @action = Action.new
  end

  def create
    @action = Action.create(task_id: @task.id, user_id: current_user.id, completed: true)
  end

  private
    def set_user
      @user = current_user
    end

  # def set_task
  #   @task = Task.find(params[:task_id])
  # end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/causes_controller.rb
# frozen_string_literal: true

class CausesController < ApplicationController
  def index
    @causes = Cause.all
    @time = 0
  end

  def show
    @cause = Cause.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user! # Ensure user is signed in

  def index
    # Fetch data related to the current user
    @causes = current_user.causes
    @tasks = current_user.tasks.order(time: :asc)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def about; end

  def how_it_works; end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  #   def index
  #     @cause = Cause.find(params[:cause_id])
  #     @tasks = Task.all
  #     if params[:max_time]
  #       @tasks = @tasks.where('time <= ?', params[:max_time])
  #     end
  #   end
  # end

  def index
    @cause = Cause.find(params[:cause_id])
    @tasks = @cause.tasks.order(time: :asc)
    max_time = params[:max_time]
    return unless params[:max_time]

    @tasks = @tasks.where('time <= ?', max_time).order(time: :asc)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def add_tasks
    @user = User.find(params[:id])
    tasks = Task.where(id: params[:task_ids])

    tasks.each do |task|
      @user.tasks << task unless @user.tasks.include?(task)
    end

    redirect_to @user, notice: 'Tasks have been added successfully.'
  end

  private

  def user_params
    params.require(:user).permit(:name, task_ids: [])
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/causes_helper.rb
# frozen_string_literal: true

module CausesHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/actions/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Actions#create</h1>
  <p>Find me in app/views/actions/create.html.erb</p>
</div>

app/views/actions/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Actions#new</h1>
  <p>Find me in app/views/actions/new.html.erb</p>
</div>

app/views/causes/index.html.erb
<!-- CAUSES -->
<div class="bg-white">
  <div class="mx-auto max-w-7xl py-12 px-6 lg:px-8 lg:py-24">
    <div class="space-y-12">
      <div class="space-y-5 sm:space-y-4 md:max-w-xl lg:max-w-3xl xl:max-w-none">
        <h2 class="font-title text-3xl font-bold tracking-tight sm:text-4xl">Step 1. Choose a Cause </h2>
        <p class="text-xl text-gray-500">Select a cause that you want to help. You can add them to your dashboard. New causes are added weekly.</p>
      </div>
      <ul role="list" class="space-y-12 sm:grid sm:grid-cols-2 sm:gap-x-6 sm:gap-y-12 sm:space-y-0 lg:grid-cols-3 lg:gap-x-8">
      <% @causes.each do |cause| %>
        <li>
        <%= link_to cause_path(cause), remote: true do %>
          <div class="space-y-4">
            <div class="aspect-w-3 aspect-h-2">
               <% if cause.photo.attached? %>
                <%= cl_image_tag cause.photo.key, class: "rounded-lg  shadow-lg object-scale-down", :gravity=>"cld-decompose_tile", :crop=>"crop" %>
               <% else %>
                <%= image_tag "12.png", class: "rounded-lg  shadow-lg" %>
               <% end %>
            </div>
            <div class="space-y-2">
              <div class="space-y-1 text-lg font-medium leading-6">
                <h3 class="font-title"><%= cause.name %></h3>
                <p class="text-gray-500"><%= cause.description %></p>
              </div>
            </div>
          </div>
          <% end %>
        </li>
        <% end %>
      </ul>


    </div>
  </div>
</div>

app/views/causes/show.html.erb
<!-- This example requires Tailwind CSS v3.0+ -->
<div class="bg-white">
  <div class="mx-auto max-w-7xl py-24 sm:px-6 sm:py-32 lg:px-8">
    <div class="relative isolate overflow-hidden bg-emerald-900 px-6 pt-16 shadow-2xl sm:rounded-3xl sm:px-16 md:pt-24 lg:flex lg:gap-x-20 lg:px-24 lg:pt-0">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" class="absolute top-1/2 left-1/2 -z-10 h-[64rem] w-[64rem] -translate-y-1/2 [mask-image:radial-gradient(closest-side,white,transparent)] sm:left-full sm:-ml-80 lg:left-1/2 lg:ml-0 lg:translate-y-0 lg:-translate-x-1/2" aria-hidden="true">
        <circle cx="512" cy="512" r="512" fill="url(#759c1415-0410-454c-8f7c-9a820de03641)" fill-opacity="0.7" />
        <defs>
          <radialGradient id="759c1415-0410-454c-8f7c-9a820de03641">
            <stop stop-color="#d1fae5"></stop>
            <stop offset="1" stop-color="#6ee7b7"></stop>
          </radialGradient>
        </defs>
      </svg>
      <div class="mx-auto max-w-md text-center lg:mx-0 lg:flex-auto lg:py-32 lg:text-left">
        <h2 class="font-title text-3xl font-bold tracking-tight text-white sm:text-4xl"><%= @cause.name %></h2>
        <p class="mt-6 text-lg leading-8 text-gray-300"><%= @cause.description %></p>
        <div class="mt-10 flex items-center justify-center gap-x-6 lg:justify-start">
          <%= link_to "Take Action", cause_tasks_path(@cause), class: "rounded-md bg-white px-3.5 py-1.5 text-base font-semibold leading-7 text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white" %>
          <a href="#" class="text-base font-semibold leading-7 text-white">Learn more <span aria-hidden="true">→</span></a>
        </div>
      </div>
      <div class="relative mt-16 h-80 lg:mt-8 object-scale-down">
        <% if @cause.photo.attached? %>
          <%= cl_image_tag @cause.photo.key, class: "object-scale-down absolute top-0 left-0 w-[57rem] max-w-none rounded-md bg-white/5 ring-1 ring-white/10", :gravity=>"cld-decompose_tile", :crop=>"crop" %>
        <% else %>
          <%= image_tag "12.png", class: "rounded-lg  shadow-lg" %>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="p-4 m-4">
<div class="overflow-hidden rounded-lg bg-white shadow">
  <h2 class="sr-only" id="profile-overview-title">Profile Overview</h2>
  <div class="bg-emerald-100 p-6">
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="sm:flex sm:space-x-5">
        <div class="flex-shrink-0">
          <img class="mx-auto h-20 w-20 rounded-full" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
        </div>
        <div class="mt-4 text-center sm:mt-0 sm:pt-1 sm:text-left">
          <p class="mx-auto mt-5 max-w-xl text-xl text-gray-500">Welcome back, <%= current_user.name %></p>
          <p class="font-title mt-1 text-3xl font-bold tracking-tight text-gray-900 sm:text-3xl lg:text-5xl">Activism Dashboard</p>
        </div>
      </div>
      <div class="mt-5 flex justify-center sm:mt-0">
        <a href="#" class="flex items-center justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">View profile</a>
      </div>
    </div>
  </div>
  <div class="grid grid-cols-1 divide-y divide-gray-200 border-t border-gray-200 bg-gray-50 sm:grid-cols-3 sm:divide-x sm:divide-y-0">
    <div class="px-6 py-5 text-center text-sm">
      <span class="font-title text-sm font-medium text-gray-500">Task Time Tracker</span> <br>
      <span class="text-sm font-bold tracking-tight text-gray-900">7 hours</span>
    </div>
    <div class="px-6 py-5 text-center text-sm font-medium">
      <span class="font-title text-base text-sm font-medium text-gray-500">Completed Tasks</span><br>
      <span class="text-sm font-bold tracking-tight text-gray-900"><%= @tasks.count %></span>
    </div>
    <div class="px-6 py-5 text-center text-sm font-medium">
      <span class="font-title text-base text-sm font-medium text-gray-500">Causes</span><br>
      <span class="text-sm font-bold tracking-tight text-gray-900"><%= @causes.count %></span>
    </div>
  </div>

<div class="flex min-h-full flex-col">

  <!-- 3 column wrapper -->
  <div class="mx-auto w-full max-w-7xl grow lg:flex xl:px-2">
    <!-- Left sidebar & main wrapper -->
    <div class="flex-1 xl:flex">
      <div class="border-b border-gray-200 px-4 py-6 sm:px-6 lg:pl-8 xl:w-64 xl:shrink-0 xl:border-b-0 xl:border-r xl:pl-6">
        <!-- Left column area -->
        <div class="p-2 m-2">
             <div class="border-b border-gray-200 pb-5">
        <h1 class="font-title text-base font-medium text-gray-500">Recent Causes</h1>
      </div>
            <% @causes.uniq { |cause| cause.id }.each do |cause| %>
            <div class="p-2 m-2">
                <%= link_to cause_path(cause) do %>
                 <%= cl_image_tag cause.photo.key, class: "rounded-lg shadow-lg", :gravity=>"cld-decompose_tile", :crop=>"crop" %>  
                <% end %>
            </div>
            <% end %>
        </div>
       
         <%= link_to causes_path, class:"flex w-full items-center justify-center rounded-md border border-transparent bg-emerald-100 px-4 py-2 text-sm font-medium text-emerald-300 hover:bg-emerald-200 md:py-4 md:px-10 md:text-lg" do %>
            <svg class="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="#6EE7B7" aria-hidden="true">
                <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
            </svg>
            New Cause
        <% end %>   
      
      </div>

      <div class="px-4 py-6 sm:px-6 lg:pl-8 xl:flex-1 xl:pl-6">
        <div class="p-2 m-2">
         <div class="border-b border-gray-200 pb-5">
        <h1 class="font-title text-base font-medium text-gray-500">Your Tasks</h1>
      </div>
        <% @tasks.each do |task| %>
          <div class="mt-5", style="display: flex; align-items: center;">
          <svg class="h-5 w-5 pr-2" viewBox="0 0 20 20" fill="#6EE7B7" aria-hidden="true">
            <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd" />
          </svg>
        <p class="text-sm text-gray-500"><%= task.name %></p>
         </div>
        <% end %>
         </div>         
    </div>
    </div>

    <div class="shrink-0 border-t border-gray-200 px-4 py-6 sm:px-6 lg:w-96 lg:border-l lg:border-t-0 lg:pr-8 xl:pr-6">
      <!-- Right column area -->
      <div class="border-b border-gray-200 pb-5">
        <h1 class="font-title text-base font-medium text-gray-500">In the News</h1>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/pages/home.html.erb
  <main class="font-title lg:relative">
    <div class="mx-auto w-full max-w-7xl pt-16 pb-20 text-center lg:py-48 lg:text-left">
      <div class="px-6 sm:px-8 lg:w-1/2 xl:pr-16">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl lg:text-5xl xl:text-6xl">
          <span class="font-title block xl:inline">Hashtag Activism</span>
            <span class="font-title block text-emerald-300 xl:inline">online actions</span>
        </h1>
        <p class="mx-auto mt-3 max-w-md text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">Turn hashtags into actions, retweets into revolutions. We map hashtags to actionable resources to empower supporters with practical remote tasks to accomplish real change.</p>
        <div class="mt-10 sm:flex sm:justify-center lg:justify-start">
          <div class="rounded-md shadow">
            <%= link_to "Get started", causes_path, class: "flex w-full items-center justify-center rounded-md border border-transparent bg-emerald-300 px-8 py-3 text-base font-medium text-white hover:bg-emerald-400 md:py-4 md:px-10 md:text-lg" %>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-3">
              <%= link_to "Live demo", how_it_works_path, class:"flex w-full items-center justify-center rounded-md border border-transparent bg-emerald-100 px-8 py-3 text-base font-medium text-emerald-300 hover:bg-emerald-200 md:py-4 md:px-10 md:text-lg" %>
            </div>
          </div>
      </div>
    </div>
    <div class="relative h-64 w-full sm:h-72 md:h-96 lg:absolute lg:inset-y-0 lg:right-0 lg:h-full lg:w-1/2">
      <%= image_tag "hero_banner.png", class: "h-56 w-full object-cover sm:h-72 md:h-96 lg:h-full lg:w-full" %>
    </div>
  </main>
</div>

<!--- how it works --->
<div class="bg-white">
  <div class="mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8">
    <div class="rounded-2xl bg-emerald-50 border border-transparent px-6 py-16 sm:p-16">
      <div class="mx-auto max-w-xl lg:max-w-none">
        <div class="text-center">
          <h2 class="font-title text-2xl font-bold tracking-tight text-gray-900">How online activism works:</h2>
        </div>
        <div class="mx-auto mt-12 grid max-w-sm grid-cols-1 gap-y-10 gap-x-8 sm:max-w-none lg:grid-cols-3">
          <div class="text-center sm:flex sm:text-left lg:block lg:text-center">
            <div class="sm:flex-shrink-0">
              <div class="flow-root">
                <img class="mx-auto h-16 w-16" src="https://tailwindui.com/img/ecommerce/icons/icon-shipping-simple.svg" alt="">
              </div>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-6 lg:mt-6 lg:ml-0">
              <h3 class="font-title text-sm font-medium text-gray-900">Cause</h3>
              <p class="mt-2 text-sm text-gray-500">Choose a cause you care about from our selection of causes. New causes are added frequently depending on the current events.</p>
            </div>
          </div>

          <div class="text-center sm:flex sm:text-left lg:block lg:text-center">
            <div class="sm:flex-shrink-0">
              <div class="flow-root">
                <img class="mx-auto h-16 w-16" src="https://tailwindui.com/img/ecommerce/icons/icon-exchange-simple.svg" alt="">
              </div>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-6 lg:mt-6 lg:ml-0">
              <h3 class="font-title text-sm font-medium text-gray-900">Time</h3>
              <p class="mt-2 text-sm text-gray-500">Select how much time you have to spend working on this cause and we'll show you doable tasks in that time period.</p>
            </div>
          </div>

          <div class="text-center sm:flex sm:text-left lg:block lg:text-center">
            <div class="sm:flex-shrink-0">
              <div class="flow-root">
                <img class="mx-auto h-16 w-16" src="https://tailwindui.com/img/ecommerce/icons/icon-warranty-simple.svg" alt="">
              </div>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-6 lg:mt-6 lg:ml-0">
              <h3 class="font-title text-sm font-medium text-gray-900">Task</h3>
              <p class="mt-2 text-sm text-gray-500">Complete the task off of your to-do list and make real change happen. View all of the tasks you've completed in one place and highlights from causes.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="relative px-6 pt-6 lg:px-8 font-title ">
<nav class="relative flex items-center justify-between sm:h-10 lg:justify-start" aria-label="Global">
  <div class="flex flex-shrink-0 flex-grow items-center lg:flex-grow-0">
    <div class="flex w-full items-center justify-between md:w-auto">
      <a>
        <span class="sr-only">Hashtag activism</span>
        <%= link_to root_path do %>
         <%= image_tag "hashtag_logo.png", class: "h-16 w-auto sm:h-16"%>
         <% end %>
      </a>
      <div class="-mr-2 flex items-center md:hidden">
        <button type="button" class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!-- Heroicon name: outline/bars-3 -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
    </div>
  </div>
  <div class="hidden md:ml-10 md:block md:space-x-8 md:pr-4">

    <%= link_to "How it works", how_it_works_path, class: "font-medium text-gray-500 hover:text-gray-900" %>

    <%= link_to "Causes", causes_path, class: "font-medium text-gray-500 hover:text-gray-900" %>

    <%= link_to "About", about_path, class: "font-medium text-gray-500 hover:text-gray-900" %>

    <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Get Involved</a>

    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
    class: "font-medium text-emerald-300 hover:text-emerald-200" %>

    <%= link_to "Sign in", new_user_session_path,
    class: "font-medium text-emerald-300 hover:text-emerald-200" %>

  </div>
</nav>
</div>

<!--
Mobile menu, show/hide based on menu open state.

Entering: "duration-150 ease-out"
  From: "opacity-0 scale-95"
  To: "opacity-100 scale-100"
Leaving: "duration-100 ease-in"
  From: "opacity-100 scale-100"
  To: "opacity-0 scale-95"
-->
<div class="absolute inset-x-0 top-0 z-10 origin-top-right transform p-2 transition md:hidden">
<div class="overflow-hidden rounded-lg bg-white shadow-md ring-1 ring-black ring-opacity-5">
  <div class="flex items-center justify-between px-5 pt-4">
    <div>
      <%= link_to root_path do %>
        <%= image_tag "hashtag_logo.png", class: "h-8 w-auto"%>
      <% end %>
    </div>
    <div class="-mr-2">
      <button type="button" class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
        <span class="sr-only">Close main menu</span>
        <!-- Heroicon name: outline/x-mark -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  </div>
  <div class="space-y-1 px-2 pt-2 pb-3">
    <%= link_to "How it works", how_it_works_path, class:"block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>

    <%= link_to "Causes", causes_path, class:"block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>

    <%= link_to "About", about_path, class:"block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900" %>

    <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-700 hover:bg-gray-50 hover:text-gray-900">Get Involved</a>
  </div>
  <a href="#" class="block w-full bg-gray-50 px-5 py-3 text-center font-medium text-indigo-600 hover:bg-gray-100">Log in</a>
</div>
</div>
</div>

app/views/tasks/index.html.erb
<div class="p-4 m-4 outline-dashed">
  <div class="grid grid-cols-6 gap-4 outline-dotted">

    <div class="col-start-2 col-span-4 outline-dashed">
       <div class="mx-auto max-w-2xl text-center outline-dashed">
        <h2 class="font-title text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Tasks for <%= @cause.name %></h2>
        <p class="mt-6 text-lg leading-8 text-gray-600"><%= @cause.description %></p>
      </div>
    </div>

    <div class="col-start-1 col-end-4 outline-dashed">
     <!----- Task filter ------->
      <%= render "shared/task_filter" %>
    <!----- Task filter ------->

      <%= form_with url: add_tasks_user_path(current_user), method: :post do |form| %>
      <div class="bg-white p-2 outline-dashed">
        <div class="mx-auto max-w-2xl text-left outline-dashed">
          <% @tasks.each do |task| %>
            <div class="divide-y divide-gray-200 m-4 p-4 overflow-hidden rounded-lg bg-gray-200 shadow sm:grid sm:grid-cols-1 sm:gap-px sm:divide-y-0">
              <div class="rounded-tl-lg rounded-tr-lg sm:rounded-tr-none relative group bg-white p-6 focus-within:ring-2 focus-within:ring-inset focus-within:ring-emerald-500">
                <div>
                  <%= check_box_tag 'task_ids[]', task.id, false, class: "h-8 w-8 rounded border-gray-300 text-emerald-600 focus:ring-emerald-500" %>
                </div>
                <!-- The rest of your code here -->
                <div class="mt-8">
                <h3 class="font-title text-lg font-medium">
                    <!-- Extend touch target to entire panel -->
                    <!-- <span class="absolute inset-0" aria-hidden="true"></span> -->
                    <%= task.name %>
                </h3>
                <p class="mt-2 text-sm text-gray-500"><%= task.content %></p>
                <p class="mt-2 text-sm text-gray-500"><%= task.time %> minutes</p>
             </div>

              <span class="absolute top-6 right-6 text-gray-300 group-hover:text-gray-400" aria-hidden="true">
              <%= link_to task.url, target: "_blank" do %>
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20 4h1a1 1 0 00-1-1v1zm-1 12a1 1 0 102 0h-2zM8 3a1 1 0 000 2V3zM3.293 19.293a1 1 0 101.414 1.414l-1.414-1.414zM19 4v12h2V4h-2zm1-1H8v2h12V3zm-.707.293l-16 16 1.414 1.414 16-16-1.414-1.414z" />
                </svg>
              <% end %>
              </span>

              </div>
            </div>
          <% end %>
          <div class="container p-2 m-2">
            <%= form.submit 'Save', class: "font-title inline-flex items-center rounded-md border border-transparent bg-emerald-300 px-8 py-3 text-base font-medium text-white hover:bg-emerald-400 md:py-4 md:px-10 md:text-lg" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>



    <div class="col-end-7 col-span-3  outline-dashed">
     <div class="p-4 m-4">
      <%= cl_image_tag @cause.photo.key, :gravity=>"cld-decompose_tile", :crop=>"crop" %>
     </div>
      <div class="container p-4 m-2">

        <ul role="list" class="divide-y divide-gray-200">
          <h1 class="font-title text-lg text-center"> Notable Organizations </h1>
          <li class="px-4 py-4 sm:px-0">
            <p> Notable organizations</p>
          </li>
          <li class="px-4 py-4 sm:px-0">
            <p> Notable organizations</p>
          </li>
          <li class="px-4 py-4 sm:px-0">
            <p> Notable organizations</p>
          </li>
          <li class="px-4 py-4 sm:px-0">
            <p> Notable organizations</p>
          </li>
        </ul>
      </div>

  </div>
    <div class="col-start-1 col-end-7 outline-dashed">
       <div class="container p-2 m-2">
        <%= link_to "Go back", cause_path(@cause), class: "font-title inline-flex items-center rounded-md border border-transparent bg-emerald-300 px-8 py-3 text-base font-medium text-white hover:bg-emerald-400 md:py-4 md:px-10 md:text-lg" %>
      </div>
    </div>
</div>